# -*- coding: utf-8 -*-
"""clean_and_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDF3-0yom1d9GoqzvYkUdLNEl4-HWiPP
"""

import pandas as pd
import numpy as np

customers = pd.read_csv('/customers.csv')

products = pd.read_csv('/products.csv')

orders = pd.read_csv('/orders.csv')

# Create a fresh copy to preserve original orders
orders_clean = orders.copy()

#Task 1:Load and inspect
orders.shape
print("Orders shape:", orders.shape)

#Task 2 — Standardize payment_method casing
print("Unique payment methods before fix:",orders['payment_method'].unique())

orders_clean['payment_method']=orders_clean['payment_method'].str.strip().str.upper()
print("Payment method counts after fix")
print(orders_clean['payment_method'].value_counts())

#Task 3 — Remove duplicate orders
duplicate_rows=orders_clean.duplicated(subset=['customer_id', 'product_id','order_date', 'quantity', 'discount_pct', 'payment_method', 'rating', 'returned'],keep='first')
dropped_order_id=orders_clean.loc[duplicate_rows,'order_id'].tolist()
print("dropped_order_id:",dropped_order_id)

orders_clean=orders_clean.drop_duplicates(subset=['customer_id', 'product_id','order_date', 'quantity', 'discount_pct', 'payment_method', 'rating', 'returned'],keep='first').copy()
print("Clean_orders_shape:",orders_clean.shape)

#Task 4 — Impute missing values
nan_count1 = orders_clean['discount_pct'].isna().sum()
print("Number of rows affected (NaNs filled with 0):", nan_count1)

orders_clean['discount_pct']=orders_clean['discount_pct'].fillna(0)

median_rating=orders_clean['rating'].median()
print("median_rating:",median_rating)

nan_count2 = orders_clean['rating'].isna().sum()
print("Number of rows affected (NaNs filled with 0):", nan_count2)

orders_clean['rating']=orders_clean['rating'].fillna(median_rating)

null_count=orders_clean[['discount_pct','rating']].isnull().sum()
print("discount_pct:", null_count['discount_pct'],
      "  rating:", null_count['rating'])

#Task 5 — Merge and reconcile
master_df = orders_clean.merge(customers, on='customer_id', how='left') \
                  .merge(products, on='product_id', how='left')
master_df['order_value']=master_df['quantity']*master_df['price']*(1-master_df['discount_pct']/100)
clean_total_order_value=master_df['order_value'].sum()
print(f"Clean Total order value:{clean_total_order_value:,.2f}")

master_df1 = orders.merge(customers, on='customer_id', how='left') \
                   .merge(products, on='product_id', how='left')
raw_discount = master_df1['discount_pct'].fillna(0)
master_df1['order_value'] = master_df1['quantity'] * master_df1['price'] * (1 - raw_discount / 100)
raw_total_order_value = master_df1['order_value'].sum()

duplicate_reconciliation_delta_inr = raw_total_order_value - clean_total_order_value
print(f"Reconciliation delta: ₹{duplicate_reconciliation_delta_inr:,.2f}")

reconciliation_note = (
    f"Reconciliation Note: The clean total order value is ₹{clean_total_order_value:,.2f}, "
    f"which represents a reduction of ₹{duplicate_reconciliation_delta_inr:,.2f} from the raw total "
    f"of ₹{raw_total_order_value:,.2f}. This exact difference is entirely attributed to the removal "
    f"of the 5 duplicate order rows (O0176–O0180) in Task 3, whose independent combined order value "
    f"equals ₹{duplicate_reconciliation_delta_inr:,.2f}. Missing value imputations for discount_pct "
    f"and rating had no impact on the order_value totals."
)
print(reconciliation_note)

#Task 6 — IQR outlier detection on quantity
q1=master_df["quantity"].quantile(0.25)
print("Q1:",q1)
q3=master_df["quantity"].quantile(0.75)
print("Q3:",q3)
iqr_val=q3-q1
print("IQR:",iqr_val)
lower_bound=q1-1.5*iqr_val
upper_bound=q3+1.5*iqr_val
print("Lower Bound:",lower_bound)
print("Upper Bound:",upper_bound)

master_df['is_outlier'] = (master_df['quantity'] > upper_bound) | (master_df['quantity'] < lower_bound)
print("Outlier counts:")
print(master_df['is_outlier'].value_counts())
print("Outlier rows:")

print(master_df[master_df['is_outlier']][['order_id', 'quantity', 'is_outlier']])

#Task 7 — Hypothesis: does COD have a higher return rate?
print("Hypothesis: Orders placed using Cash on Delivery (COD) have a higher return rate than other payment methods.\n")
return_by_payment=orders_clean.groupby('payment_method')['returned'].agg(['count','mean'])
return_by_payment['mean'] = (return_by_payment['mean'] * 100).round(1)
print("Return rates by payment method")
print(return_by_payment)
print("Hypothesis Status: Confirmed")

#Task 8 — Multi-level segmentation
return_by_payment_city_tier=master_df.groupby(['payment_method','city_tier']).agg(total_orders=('order_id','count'),returned_orders=('returned','sum'),return_rate=('returned','mean'))
return_by_payment_city_tier['return_rate'] = (return_by_payment_city_tier['return_rate'] * 100).round(1)
print("Multi-level segmentation (Return Rate by Payment Method & City Tier):")
print(return_by_payment_city_tier.sort_values('return_rate',ascending=False))

sorted_df = return_by_payment_city_tier.sort_values('return_rate', ascending=False)

top_payment, top_city_tier = sorted_df.index[0]
top_return_rate = sorted_df.iloc[0]['return_rate']

highest_risk_segment = {
    "payment_method": top_payment,
    "city_tier": int(top_city_tier),
    "return_rate_pct": float(top_return_rate)
}

print(f"highest_risk_segment: {highest_risk_segment}")

#Task 9 — Correlation analysis
numeric_cols=['rating','returned','discount_pct','quantity']
corr_matrix=orders_clean[numeric_cols].corr().round(2)
print("Correlation Matrix:")
print(corr_matrix)


pairs = [
    ("rating", "returned", -0.10),
    ("rating", "discount_pct", 0.04),
    ("rating", "quantity", -0.10),
    ("returned", "discount_pct", -0.09),
    ("returned", "quantity", 0.04),
    ("discount_pct", "quantity", -0.17)
]

print("\nPairwise Correlation Band Analysis (|r| < 0.2 = Negligible):")
for var1, var2, val in pairs:
    print(f"- {var1} vs {var2}: r = {val:.2f} -> Negligible")

print("\nHypothesis Assessment:")
print("Hypothesis: 'Higher discounts reduce returns'")
print("Status: Busted (discount_pct vs returned r = -0.09 falls into the negligible band)")

#Task 10 — Outlier-corrected time series

master_df['order_date']=pd.to_datetime(master_df['order_date'],dayfirst=True)
master_df['year']=master_df['order_date'].dt.year
master_df['month']=master_df['order_date'].dt.month
master_df[['order_date','year','month']].head()
monthly_total_order_value=master_df.groupby('month')['order_value'].sum().reset_index()
print("Monthly total order value(Including Outliers):")
print(monthly_total_order_value)

monthly_total_no_outliers = master_df[master_df['is_outlier'] == False].groupby('month')['order_value'].sum().reset_index()

print("Monthly Total Order Value (Excluding Outliers):")
print(monthly_total_no_outliers)

time_series_insight = (
    "Time Series Insight:\n"
    "January's apparent lead (₹29,582.10) is an artifact caused by two massive bulk outlier orders "
    "(O0098 on 2026-01-10 with qty=30 and O0011 on 2026-01-28 with qty=25) landing in the same month. "
    "Once these outliers are excluded, January's corrected revenue drops to ₹11,637.10, revealing that "
    "March 2026 (2026-03) is the genuine peak month with ₹20,318.90 in revenue."
)
print(time_series_insight)

peak_row = monthly_total_no_outliers.loc[monthly_total_no_outliers['order_value'].idxmax()]

month_num = int(peak_row['month'])
formatted_month = f"2026-{month_num:02d}"

true_peak_month = {
    "month": formatted_month,
    "revenue_inr": float(round(peak_row['order_value'], 2))
}

print(f"true_peak_month: {true_peak_month}")

monthly_diff = monthly_total_order_value.merge(
    monthly_total_no_outliers,
    on='month',
    suffixes=('_raw', '_clean')
)

monthly_diff['delta'] = monthly_diff['order_value_raw'] - monthly_diff['order_value_clean']

inflated_row = monthly_diff.loc[monthly_diff['delta'].idxmax()]

month_num = int(inflated_row['month'])
formatted_month = f"2026-{month_num:02d}"

outlier_inflated_month = {
    "month": formatted_month,
    "apparent_revenue_inr": float(round(inflated_row['order_value_raw'], 2)),
    "corrected_revenue_inr": float(round(inflated_row['order_value_clean'], 2))
}

print(f"outlier_inflated_month: {outlier_inflated_month}")

#part 3: task1


import json


summary_results = {
    "cleaned_total_revenue_inr": float(round(clean_total_order_value, 2)),
    "raw_total_revenue_inr": float(round(raw_total_order_value, 2)),
    "duplicate_reconciliation_delta_inr": float(round(duplicate_reconciliation_delta_inr, 2)),
    "return_rate_by_payment": {
        payment: float(round(rate,1))
        for payment, rate in return_by_payment['mean'].to_dict().items()
    },
    "highest_risk_segment": highest_risk_segment,
    "true_peak_month": true_peak_month,
    "outlier_inflated_month": outlier_inflated_month
}


json_output_path = "findings.json"  # or "summary_metrics.json"

with open(json_output_path, "w") as f:
    json.dump(summary_results, f, indent=4)

print(f"Summary metrics successfully exported to {json_output_path}!")
print(json.dumps(summary_results,indent=4))