# -*- coding: utf-8 -*-
"""clean_and_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDF3-0yom1d9GoqzvYkUdLNEl4-HWiPP
"""

import pandas as pd
import numpy as np

customers = pd.read_csv('/customers.csv')

products = pd.read_csv('/products.csv')

orders = pd.read_csv('/orders.csv')

# Create a fresh copy to preserve original orders
orders_clean = orders.copy()

orders.shape
print("Orders shape:", orders.shape)

print(orders['payment_method'].unique())

orders_clean['payment_method']=orders_clean['payment_method'].str.strip().str.upper()
print(orders_clean['payment_method'].value_counts())

duplicate_rows=orders_clean.duplicated(subset=['customer_id', 'product_id','order_date', 'quantity', 'discount_pct', 'payment_method', 'rating', 'returned'],keep='first')
dropped_order_id=orders_clean.loc[duplicate_rows,'order_id'].tolist()
print("dropped_order_id:",dropped_order_id)

orders_clean=orders_clean.drop_duplicates(subset=['customer_id', 'product_id','order_date', 'quantity', 'discount_pct', 'payment_method', 'rating', 'returned'],keep='first').copy()
print("Clean_orders_shape:",orders_clean.shape)
nan_count1 = orders_clean['discount_pct'].isna().sum()
print("Number of rows affected (NaNs filled with 0):", nan_count1)

orders_clean['discount_pct']=orders_clean['discount_pct'].fillna(0)

median_rating=orders_clean['rating'].median()
print("median_rating:",median_rating)

nan_count2 = orders_clean['rating'].isna().sum()
print("Number of rows affected (NaNs filled with 0):", nan_count2)

orders_clean['rating']=orders_clean['rating'].fillna(median_rating)

nan_count3=orders_clean[['discount_pct','rating']].isnull().sum()
print("discount_pct:", nan_count3['discount_pct'],
      "  rating:", nan_count3['rating'])

master_df = orders_clean.merge(customers, on='customer_id', how='left') \
                  .merge(products, on='product_id', how='left')
master_df['order_value']=master_df['quantity']*master_df['price']*(1-master_df['discount_pct']/100)
total_order_value=master_df['order_value'].sum()
print(f"Total order value:{total_order_value:,.2f}")

q1=master_df["quantity"].quantile(0.25)
print(q1)
q3=master_df["quantity"].quantile(0.75)
print(q3)
iqr_val=q3-q1
print(iqr_val)
lower_bound=q1-1.5*iqr_val
upper_bound=q3+1.5*iqr_val
print(lower_bound)
print(upper_bound)

master_df['is_outlier'] = (master_df['quantity'] > upper_bound) | (master_df['quantity'] < lower_bound)

print(master_df['is_outlier'].value_counts())

print(master_df[master_df['is_outlier']][['order_id', 'quantity', 'is_outlier']])

return_by_payment=orders_clean.groupby('payment_method')['returned'].agg(['count','mean'])
return_by_payment['mean'] = (return_by_payment['mean'] * 100).round(2)
print(return_by_payment)

return_by_payment_city_tier=master_df.groupby(['payment_method','city_tier']).agg(total_orders=('order_id','count'),returned_orders=('returned','sum'),return_rate=('returned','mean')).round(3)
return_by_payment_city_tier['return_rate'] = (return_by_payment_city_tier['return_rate'] * 100).round(2)
print(return_by_payment_city_tier.sort_values('return_rate',ascending=False))

numeric_cols=['rating','returned','discount_pct','quantity']
corr_matrix=orders_clean[numeric_cols].corr().round(2)
print(corr_matrix)

master_df.head()
master_df['order_date']=pd.to_datetime(master_df['order_date'],dayfirst=True)
master_df['year']=master_df['order_date'].dt.year
master_df['month']=master_df['order_date'].dt.month
master_df[['order_date','year','month']].head()
monthly_total_order_value=master_df.groupby('month')['order_value'].sum().reset_index()
print("Monthly total order value:")
print(monthly_total_order_value)

monthly_total_no_outliers = master_df[master_df['is_outlier'] == False].groupby('month')['order_value'].sum().reset_index()

print("Monthly Total Order Value (Excluding Outliers):")
print(monthly_total_no_outliers)