# -*- coding: utf-8 -*-
"""visualize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xJA5w3huNzCGtV7WiCbJp62Y89RBoEHR
"""

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from clean_and_eda import return_by_payment, monthly_total_no_outliers

return_by_payment = return_by_payment.sort_values(by='mean', ascending=False)
import matplotlib.pyplot as plt
colors=[]
for payment_method in return_by_payment.index:
  if payment_method=='COD':
    colors.append('#ff6666')
  elif payment_method=='CARD':
    colors.append('#1a75ff')
  else:
    colors.append('#ff1aff')
fig,ax=plt.subplots(figsize=(8,5))

bars=ax.bar(return_by_payment.index,return_by_payment['mean'],color=colors)
ax.bar_label(bars,fmt='%.1f%%',fontweight='bold')
ax.set_title("COD Returns at44.4%-3x Card")
ax.set_xlabel("Payment Method", fontweight='bold', labelpad=10)
ax.set_ylabel("Return Rate (%)", fontweight='bold', labelpad=10)
plt.savefig('return_rate_by_payment.png', bbox_inches='tight')
plt.show()

monthly_total_no_outliers = monthly_total_no_outliers.sort_values('month')

month_map = {1: 'Jan', 2: 'Feb', 3: 'March', 4: 'April', 5: 'May', 6: 'June'}
monthly_total_no_outliers['month_name'] = monthly_total_no_outliers['month'].map(month_map)


fig, ax = plt.subplots(figsize=(9, 5))

ax.plot(
    monthly_total_no_outliers['month_name'],
    monthly_total_no_outliers['order_value'],
    marker='o',
    color='#1f77b4',
    linewidth=2
)


ax.set_title("March is the actual peak revenue month", fontsize=12, fontweight='bold')
ax.set_xlabel("Month",fontweight='bold', labelpad=10)
ax.set_ylabel("Monthly Revenue",fontweight='bold', labelpad=10)

ax.yaxis.set_major_formatter(ticker.StrMethodFormatter('{x:,.0f}'))


plt.tight_layout()
plt.savefig('monthly_revenue_trend.png', dpi=150, bbox_inches='tight')
plt.show()



